[package]
name = "test_client"
version = "0.1.0"
edition = "2024"

[dependencies]
rasterizeddb_core = { path = "../rasterizeddb_core" }
tokio = { version = "1", features = ["full"] }
stopwatch = "0.0.7"
env_logger = "0.11"
log = "0.4"
rand = "0.9"
futures = "0.3"