[package]
name = "rastcp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
rustls = { version = "0.23.23" }
tokio-rustls = "0.26.2"
rustls-pemfile = "2.2.0"
thiserror = "2.0.11"
log = "0.4.26"
env_logger = "0.11.6"
futures-util = "0.3.31"
bytes = "1.10.0"
rcgen = { version = "0.13.2", default-features = false, features = ["aws_lc_rs", "pem"] }
time = "0.3.37"

[dev-dependencies]
serde_json = "1.0.140"
bincode = "1.3.3"
serde = { version = "1.0.218", features = ["derive"] }
uuid = "1.15.1"