[package]
name = "test_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
dashmap = "6.1.0"
async-lazy = { version = "0.1.0", features = ["parking_lot"] }
ahash = "0.8.11"